title: Jung Sup Lee's Website
email: jlee4255@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Jung Sup Lee's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jungsuplee-com.pages.dev" # the base hostname & protocol for your site
github_username: jlee4255

markdown: kramdown
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
